# Generated by Django 6.0.5 on 2026-05-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0004_adocao_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='correspondido',
            field=models.BooleanField(default=False),
        ),
    ]
