# Generated by Django 6.0.5 on 2026-05-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0005_carta_correspondido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtida',
            name='carta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='cartas.carta'),
        ),
    ]
