# Generated by Django 6.0.5 on 2026-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_endereco_perfil_nome_alter_perfil_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rua',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
